services:
  - type: web
    name: frontend
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://beb-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html